import type {
  AssetDependency,
  MetricDefinition,
  MaintenanceEvent,
  Operator,
  AuditEvent,
} from "@maitri-bharati/shared";

export const hardeningSeedData: {
  dependencies: AssetDependency[];
  metricDefinitions: MetricDefinition[];
  maintenanceEvents: MaintenanceEvent[];
  operators: Operator[];
  auditEvents: AuditEvent[];
} = {
  // ─── 1. Asset Dependencies ──────────────────────────────────────
  dependencies: [
    // Maitri Station Dependency Chains:
    // GENERATOR -> BATTERY & ENERGY -> HVAC / WATER / COMMS -> MAIN COMPLEX
    {
      id: "dep-maitri-gen1-bat",
      fromAssetId: "asset-maitri-gen-1",
      toAssetId: "asset-maitri-bat-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "Primary Generator 1 charges the central Lithium battery bank",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-gen1-hvac",
      fromAssetId: "asset-maitri-gen-1",
      toAssetId: "asset-maitri-hvac-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "Primary Generator 1 provides 3-phase electrical power to main HVAC air handlers",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-gen1-wtr",
      fromAssetId: "asset-maitri-gen-1",
      toAssetId: "asset-maitri-water-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "Primary Generator 1 energizes Priyadarshini lake submersible pumps and heat-tracing",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-gen1-com",
      fromAssetId: "asset-maitri-gen-1",
      toAssetId: "asset-maitri-comm-1",
      dependencyType: "POWER",
      criticality: "HIGH",
      description: "Generator 1 supplies polar satellite comms radome power",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-gen2-bat",
      fromAssetId: "asset-maitri-gen-2",
      toAssetId: "asset-maitri-bat-1",
      dependencyType: "POWER",
      criticality: "HIGH",
      description: "Standby Generator 2 serves as failover power source for the battery bank",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-hvac-bld",
      fromAssetId: "asset-maitri-hvac-1",
      toAssetId: "asset-maitri-bld-main",
      dependencyType: "THERMAL",
      criticality: "CRITICAL",
      description: "HVAC provides heated air circulation preventing habitat freeze-up",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-wtr-bld",
      fromAssetId: "asset-maitri-water-1",
      toAssetId: "asset-maitri-bld-main",
      dependencyType: "WATER",
      criticality: "CRITICAL",
      description: "Priyadarshini water system supplies potable water to living modules",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-com-bld",
      fromAssetId: "asset-maitri-comm-1",
      toAssetId: "asset-maitri-bld-main",
      dependencyType: "DATA",
      criticality: "HIGH",
      description: "Satellite terminal provides remote operations telemetry and data links",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },

    // Bharati Station Dependency Chains:
    // CHP 1 -> BATTERY & THERMAL BUS -> RO / HVAC / GROUND SAT -> MAIN STILT COMPLEX
    {
      id: "dep-bharati-chp1-bat",
      fromAssetId: "asset-bharati-chp-1",
      toAssetId: "asset-bharati-bat-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "Tri-generation CHP Unit 1 powers the station 120 kWh battery storage",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-chp1-hvac",
      fromAssetId: "asset-bharati-chp-1",
      toAssetId: "asset-bharati-hvac-1",
      dependencyType: "THERMAL",
      criticality: "CRITICAL",
      description: "CHP 1 exhaust and jacket heat exchanger provides thermal bus for station heating",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-chp1-ro",
      fromAssetId: "asset-bharati-chp-1",
      toAssetId: "asset-bharati-ro-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "CHP 1 runs high-pressure seawater reverse osmosis pumps",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-chp1-sat",
      fromAssetId: "asset-bharati-chp-1",
      toAssetId: "asset-bharati-ground-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "CHP 1 feeds ISRO/NRSC polar satellite tracking dish drive motors",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-wnd1-bat",
      fromAssetId: "asset-bharati-wnd-1",
      toAssetId: "asset-bharati-bat-1",
      dependencyType: "POWER",
      criticality: "MEDIUM",
      description: "Vertical-axis polar wind array supplements battery charging during katabatic winds",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-ro-bld",
      fromAssetId: "asset-bharati-ro-1",
      toAssetId: "asset-bharati-bld-main",
      dependencyType: "WATER",
      criticality: "CRITICAL",
      description: "Desalinated water feeds the main integrated modular habitat",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-hvac-bld",
      fromAssetId: "asset-bharati-hvac-1",
      toAssetId: "asset-bharati-bld-main",
      dependencyType: "THERMAL",
      criticality: "CRITICAL",
      description: "Climate recovery system maintains interior 21C habitat condition",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
  ],

  // ─── 2. Metric Definitions ──────────────────────────────────────
  metricDefinitions: [
    {
      id: "mdef-ambient-temp",
      metric: "ambient_temperature",
      canonicalUnit: "degC",
      minPlausible: -75.0,
      maxPlausible: 25.0,
      warningThresholdLow: -45.0,
      warningThresholdHigh: 5.0,
      criticalThresholdLow: -60.0,
      criticalThresholdHigh: 12.0,
      expectedSamplingIntervalSeconds: 10,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["BUILDING", "OTHER"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-wind-speed",
      metric: "wind_speed",
      canonicalUnit: "m/s",
      minPlausible: 0.0,
      maxPlausible: 100.0,
      warningThresholdHigh: 28.0,
      criticalThresholdHigh: 45.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "MAX",
      allowedAssetTypes: ["BUILDING", "OTHER"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-pressure",
      metric: "atmospheric_pressure",
      canonicalUnit: "hPa",
      minPlausible: 850.0,
      maxPlausible: 1100.0,
      warningThresholdLow: 940.0,
      criticalThresholdLow: 915.0,
      expectedSamplingIntervalSeconds: 30,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["BUILDING", "OTHER"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-gen-temp",
      metric: "temperature",
      canonicalUnit: "degC",
      minPlausible: -40.0,
      maxPlausible: 125.0,
      warningThresholdHigh: 85.0,
      criticalThresholdHigh: 95.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["GENERATOR", "HVAC", "WATER_SYSTEM"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-power-kw",
      metric: "power_output_kw",
      canonicalUnit: "kW",
      minPlausible: 0.0,
      maxPlausible: 600.0,
      warningThresholdHigh: 185.0,
      criticalThresholdHigh: 220.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["GENERATOR", "SOLAR", "OTHER"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-fuel-rate",
      metric: "fuel_consumption_lph",
      canonicalUnit: "L/h",
      minPlausible: 0.0,
      maxPlausible: 150.0,
      warningThresholdHigh: 45.0,
      criticalThresholdHigh: 60.0,
      expectedSamplingIntervalSeconds: 10,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["GENERATOR"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-voltage",
      metric: "voltage",
      canonicalUnit: "V",
      minPlausible: 0.0,
      maxPlausible: 650.0,
      warningThresholdLow: 360.0,
      warningThresholdHigh: 440.0,
      criticalThresholdLow: 340.0,
      criticalThresholdHigh: 460.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["BATTERY", "GENERATOR"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-soc",
      metric: "state_of_charge_pct",
      canonicalUnit: "%",
      minPlausible: 0.0,
      maxPlausible: 100.0,
      warningThresholdLow: 35.0,
      criticalThresholdLow: 20.0,
      expectedSamplingIntervalSeconds: 10,
      aggregationStrategy: "LAST",
      allowedAssetTypes: ["BATTERY"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-wtr-temp",
      metric: "water_temperature",
      canonicalUnit: "degC",
      minPlausible: -5.0,
      maxPlausible: 50.0,
      warningThresholdLow: 2.5,
      criticalThresholdLow: 1.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["WATER_SYSTEM"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-flow-rate",
      metric: "flow_rate_lpm",
      canonicalUnit: "L/min",
      minPlausible: 0.0,
      maxPlausible: 300.0,
      warningThresholdLow: 25.0,
      criticalThresholdLow: 10.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["WATER_SYSTEM"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-indoor-temp",
      metric: "indoor_temperature",
      canonicalUnit: "degC",
      minPlausible: 0.0,
      maxPlausible: 40.0,
      warningThresholdLow: 17.5,
      warningThresholdHigh: 25.0,
      criticalThresholdLow: 13.0,
      criticalThresholdHigh: 28.0,
      expectedSamplingIntervalSeconds: 15,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["HVAC", "BUILDING"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-hvac-load",
      metric: "thermal_load_kw",
      canonicalUnit: "kW",
      minPlausible: 0.0,
      maxPlausible: 150.0,
      warningThresholdHigh: 65.0,
      criticalThresholdHigh: 80.0,
      expectedSamplingIntervalSeconds: 10,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["HVAC"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-packet-loss",
      metric: "packet_loss_pct",
      canonicalUnit: "%",
      minPlausible: 0.0,
      maxPlausible: 100.0,
      warningThresholdHigh: 20.0,
      criticalThresholdHigh: 50.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["COMMUNICATION"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-latency",
      metric: "latency_ms",
      canonicalUnit: "ms",
      minPlausible: 50.0,
      maxPlausible: 4000.0,
      warningThresholdHigh: 1200.0,
      criticalThresholdHigh: 2000.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["COMMUNICATION"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-snr-db",
      metric: "snr_db",
      canonicalUnit: "dB",
      minPlausible: 0.0,
      maxPlausible: 40.0,
      warningThresholdLow: 8.0,
      criticalThresholdLow: 4.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["COMMUNICATION"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
  ],

  // ─── 3. Maintenance Events ──────────────────────────────────────
  maintenanceEvents: [
    {
      id: "maint-maitri-gen1-001",
      stationId: "station-maitri",
      assetId: "asset-maitri-gen-1",
      maintenanceType: "PREVENTIVE",
      scheduledAt: new Date("2026-09-15T08:00:00Z"),
      completedAt: new Date("2026-09-15T12:30:00Z"),
      notes: "250-hour routine oil change, fuel pre-filter replacement, injector nozzle inspection.",
      partsUsed: ["Aviation-grade Arctic synthetic oil 15W-40 (45L)", "Donaldson fuel separator element (2x)"],
      result: "SUCCESS",
      createdAt: new Date("2026-09-15T08:00:00Z"),
    },
    {
      id: "maint-maitri-wtr-001",
      stationId: "station-maitri",
      assetId: "asset-maitri-water-1",
      maintenanceType: "INSPECTION",
      scheduledAt: new Date("2026-09-20T10:00:00Z"),
      completedAt: new Date("2026-09-20T11:45:00Z"),
      notes: "Priyadarshini lake pump heat-tracing cable thermal resistance test. Insulation resistance measured at 120 M-ohm.",
      partsUsed: ["Thermal heat-shrink sleeve (2m)"],
      result: "SUCCESS",
      createdAt: new Date("2026-09-20T10:00:00Z"),
    },
    {
      id: "maint-bharati-chp1-001",
      stationId: "station-bharati",
      assetId: "asset-bharati-chp-1",
      maintenanceType: "CORRECTIVE",
      scheduledAt: new Date("2026-09-22T06:00:00Z"),
      completedAt: new Date("2026-09-22T09:15:00Z"),
      notes: "Exhaust gas temperature sensor thermocouple replacement due to drift on cylinder #4.",
      partsUsed: ["Type-K Arctic thermocouple probe", "High-temp gasket seal"],
      result: "SUCCESS",
      createdAt: new Date("2026-09-22T06:00:00Z"),
    },
    {
      id: "maint-bharati-ro-001",
      stationId: "station-bharati",
      assetId: "asset-bharati-ro-1",
      maintenanceType: "PREVENTIVE",
      scheduledAt: new Date("2026-09-26T14:00:00Z"),
      completedAt: new Date("2026-09-26T17:00:00Z"),
      notes: "Desalination membrane chemical wash and citric acid descaling. Feed permeate conductivity returned to 140 ppm.",
      partsUsed: ["RO membrane cleaner compound B (5 kg)", "Micron sediment pre-filter cartridge (1x)"],
      result: "SUCCESS",
      createdAt: new Date("2026-09-26T14:00:00Z"),
    },
  ],

  // ─── 4. Operators & Roles ───────────────────────────────────────
  operators: [
    {
      id: "op-admin-01",
      username: "rsharma",
      fullName: "Col. Rajesh Sharma",
      role: "ADMIN",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-eng-maitri",
      username: "pdeshmukh",
      fullName: "Dr. Pranav Deshmukh",
      role: "ENGINEER",
      stationId: "station-maitri",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-log-maitri",
      username: "kraman",
      fullName: "Kavita Raman",
      role: "LOGISTICS",
      stationId: "station-maitri",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-eng-bharati",
      username: "sbanerjee",
      fullName: "Sourav Banerjee",
      role: "ENGINEER",
      stationId: "station-bharati",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-viewer-ops",
      username: "opsviewer",
      fullName: "Antarctic Operations Center Duty Desk",
      role: "VIEWER",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
  ],

  // ─── 5. Audit Events ────────────────────────────────────────────
  auditEvents: [
    {
      id: "audit-001",
      operatorId: "op-admin-01",
      action: "STATION_SYNC_POLICY_UPDATE",
      targetType: "STATION",
      targetId: "station-maitri",
      previousState: { dataMode: "EXTERNAL", syncIntervalSeconds: 60 },
      newState: { dataMode: "SIMULATED", syncIntervalSeconds: 3 },
      result: "SUCCESS",
      correlationId: "corr-sync-setup-01",
      createdAt: new Date("2026-09-28T09:00:00Z"),
    },
    {
      id: "audit-002",
      operatorId: "op-eng-maitri",
      action: "ACKNOWLEDGE_ALERT",
      targetType: "ALERT",
      targetId: "alert-maitri-gen-001",
      previousState: { status: "OPEN" },
      newState: { status: "ACKNOWLEDGED", comment: "Inspected fuel filter pressure differential" },
      result: "SUCCESS",
      correlationId: "corr-alert-ack-99",
      createdAt: new Date("2026-09-28T16:20:00Z"),
    },
    {
      id: "audit-003",
      operatorId: "op-eng-bharati",
      action: "SIMULATED_TEST_RUN",
      targetType: "ASSET",
      targetId: "asset-bharati-chp-2",
      previousState: { status: "MAINTENANCE" },
      newState: { status: "OPERATIONAL" },
      result: "SUCCESS",
      correlationId: "corr-chp2-test-01",
      createdAt: new Date("2026-09-29T02:15:00Z"),
    },
  ],
};
