import type {
  AssetDependency,
  MetricDefinition,
  MaintenanceEvent,
  Operator,
  AuditEvent,
  CargoMission,
  CargoRequisition,
  StationThreshold,
  MissionEvent,
} from "@maitri-bharati/shared";

export const hardeningSeedData: {
  dependencies: AssetDependency[];
  metricDefinitions: MetricDefinition[];
  maintenanceEvents: MaintenanceEvent[];
  operators: Operator[];
  auditEvents: AuditEvent[];
  cargoMissions: CargoMission[];
  cargoRequisitions: CargoRequisition[];
  stationThresholds: StationThreshold[];
  missionEvents: MissionEvent[];
} = {
  // ─── 1. Asset Dependencies ──────────────────────────────────────
  dependencies: [
    // Maitri Station Dependency Chains:
    // GENERATOR -> BATTERY & ENERGY -> HVAC / WATER / COMMS -> MAIN COMPLEX
    {
      id: "dep-maitri-gen1-bat",
      fromAssetId: "asset-maitri-gen-1",
      toAssetId: "asset-maitri-bat-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "Primary Generator 1 charges the central Lithium battery bank",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-gen1-hvac",
      fromAssetId: "asset-maitri-gen-1",
      toAssetId: "asset-maitri-hvac-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "Primary Generator 1 provides 3-phase electrical power to main HVAC air handlers",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-gen1-wtr",
      fromAssetId: "asset-maitri-gen-1",
      toAssetId: "asset-maitri-water-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "Primary Generator 1 energizes Priyadarshini lake submersible pumps and heat-tracing",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-gen1-com",
      fromAssetId: "asset-maitri-gen-1",
      toAssetId: "asset-maitri-comm-1",
      dependencyType: "POWER",
      criticality: "HIGH",
      description: "Generator 1 supplies polar satellite comms radome power",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-gen2-bat",
      fromAssetId: "asset-maitri-gen-2",
      toAssetId: "asset-maitri-bat-1",
      dependencyType: "POWER",
      criticality: "HIGH",
      description: "Standby Generator 2 serves as failover power source for the battery bank",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-hvac-bld",
      fromAssetId: "asset-maitri-hvac-1",
      toAssetId: "asset-maitri-bld-main",
      dependencyType: "THERMAL",
      criticality: "CRITICAL",
      description: "HVAC provides heated air circulation preventing habitat freeze-up",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-wtr-bld",
      fromAssetId: "asset-maitri-water-1",
      toAssetId: "asset-maitri-bld-main",
      dependencyType: "WATER",
      criticality: "CRITICAL",
      description: "Priyadarshini water system supplies potable water to living modules",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-maitri-com-bld",
      fromAssetId: "asset-maitri-comm-1",
      toAssetId: "asset-maitri-bld-main",
      dependencyType: "DATA",
      criticality: "HIGH",
      description: "Satellite terminal provides remote operations telemetry and data links",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },

    // Bharati Station Dependency Chains:
    // CHP 1 -> BATTERY & THERMAL BUS -> RO / HVAC / GROUND SAT -> MAIN STILT COMPLEX
    {
      id: "dep-bharati-chp1-bat",
      fromAssetId: "asset-bharati-chp-1",
      toAssetId: "asset-bharati-bat-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "Tri-generation CHP Unit 1 powers the station 120 kWh battery storage",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-chp1-hvac",
      fromAssetId: "asset-bharati-chp-1",
      toAssetId: "asset-bharati-hvac-1",
      dependencyType: "THERMAL",
      criticality: "CRITICAL",
      description: "CHP 1 exhaust and jacket heat exchanger provides thermal bus for station heating",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-chp1-ro",
      fromAssetId: "asset-bharati-chp-1",
      toAssetId: "asset-bharati-ro-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "CHP 1 runs high-pressure seawater reverse osmosis pumps",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-chp1-sat",
      fromAssetId: "asset-bharati-chp-1",
      toAssetId: "asset-bharati-ground-1",
      dependencyType: "POWER",
      criticality: "CRITICAL",
      description: "CHP 1 feeds ISRO/NRSC polar satellite tracking dish drive motors",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-wnd1-bat",
      fromAssetId: "asset-bharati-wnd-1",
      toAssetId: "asset-bharati-bat-1",
      dependencyType: "POWER",
      criticality: "MEDIUM",
      description: "Vertical-axis polar wind array supplements battery charging during katabatic winds",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-ro-bld",
      fromAssetId: "asset-bharati-ro-1",
      toAssetId: "asset-bharati-bld-main",
      dependencyType: "WATER",
      criticality: "CRITICAL",
      description: "Desalinated water feeds the main integrated modular habitat",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "dep-bharati-hvac-bld",
      fromAssetId: "asset-bharati-hvac-1",
      toAssetId: "asset-bharati-bld-main",
      dependencyType: "THERMAL",
      criticality: "CRITICAL",
      description: "Climate recovery system maintains interior 21C habitat condition",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
  ],

  // ─── 2. Metric Definitions ──────────────────────────────────────
  metricDefinitions: [
    {
      id: "mdef-ambient-temp",
      metric: "ambient_temperature",
      canonicalUnit: "degC",
      minPlausible: -75.0,
      maxPlausible: 25.0,
      warningThresholdLow: -45.0,
      warningThresholdHigh: 5.0,
      criticalThresholdLow: -60.0,
      criticalThresholdHigh: 12.0,
      expectedSamplingIntervalSeconds: 10,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["BUILDING", "OTHER"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-wind-speed",
      metric: "wind_speed",
      canonicalUnit: "m/s",
      minPlausible: 0.0,
      maxPlausible: 100.0,
      warningThresholdHigh: 28.0,
      criticalThresholdHigh: 45.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "MAX",
      allowedAssetTypes: ["BUILDING", "OTHER"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-pressure",
      metric: "atmospheric_pressure",
      canonicalUnit: "hPa",
      minPlausible: 850.0,
      maxPlausible: 1100.0,
      warningThresholdLow: 940.0,
      criticalThresholdLow: 915.0,
      expectedSamplingIntervalSeconds: 30,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["BUILDING", "OTHER"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-gen-temp",
      metric: "temperature",
      canonicalUnit: "degC",
      minPlausible: -40.0,
      maxPlausible: 125.0,
      warningThresholdHigh: 85.0,
      criticalThresholdHigh: 95.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["GENERATOR", "HVAC", "WATER_SYSTEM"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-power-kw",
      metric: "power_output_kw",
      canonicalUnit: "kW",
      minPlausible: 0.0,
      maxPlausible: 600.0,
      warningThresholdHigh: 185.0,
      criticalThresholdHigh: 220.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["GENERATOR", "SOLAR", "OTHER"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-fuel-rate",
      metric: "fuel_consumption_lph",
      canonicalUnit: "L/h",
      minPlausible: 0.0,
      maxPlausible: 150.0,
      warningThresholdHigh: 45.0,
      criticalThresholdHigh: 60.0,
      expectedSamplingIntervalSeconds: 10,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["GENERATOR"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-voltage",
      metric: "voltage",
      canonicalUnit: "V",
      minPlausible: 0.0,
      maxPlausible: 650.0,
      warningThresholdLow: 360.0,
      warningThresholdHigh: 440.0,
      criticalThresholdLow: 340.0,
      criticalThresholdHigh: 460.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["BATTERY", "GENERATOR"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-soc",
      metric: "state_of_charge_pct",
      canonicalUnit: "%",
      minPlausible: 0.0,
      maxPlausible: 100.0,
      warningThresholdLow: 35.0,
      criticalThresholdLow: 20.0,
      expectedSamplingIntervalSeconds: 10,
      aggregationStrategy: "LAST",
      allowedAssetTypes: ["BATTERY"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-wtr-temp",
      metric: "water_temperature",
      canonicalUnit: "degC",
      minPlausible: -5.0,
      maxPlausible: 50.0,
      warningThresholdLow: 2.5,
      criticalThresholdLow: 1.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["WATER_SYSTEM"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-flow-rate",
      metric: "flow_rate_lpm",
      canonicalUnit: "L/min",
      minPlausible: 0.0,
      maxPlausible: 300.0,
      warningThresholdLow: 25.0,
      criticalThresholdLow: 10.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["WATER_SYSTEM"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-indoor-temp",
      metric: "indoor_temperature",
      canonicalUnit: "degC",
      minPlausible: 0.0,
      maxPlausible: 40.0,
      warningThresholdLow: 17.5,
      warningThresholdHigh: 25.0,
      criticalThresholdLow: 13.0,
      criticalThresholdHigh: 28.0,
      expectedSamplingIntervalSeconds: 15,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["HVAC", "BUILDING"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-hvac-load",
      metric: "thermal_load_kw",
      canonicalUnit: "kW",
      minPlausible: 0.0,
      maxPlausible: 150.0,
      warningThresholdHigh: 65.0,
      criticalThresholdHigh: 80.0,
      expectedSamplingIntervalSeconds: 10,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["HVAC"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-packet-loss",
      metric: "packet_loss_pct",
      canonicalUnit: "%",
      minPlausible: 0.0,
      maxPlausible: 100.0,
      warningThresholdHigh: 20.0,
      criticalThresholdHigh: 50.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["COMMUNICATION"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-latency",
      metric: "latency_ms",
      canonicalUnit: "ms",
      minPlausible: 50.0,
      maxPlausible: 4000.0,
      warningThresholdHigh: 1200.0,
      criticalThresholdHigh: 2000.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["COMMUNICATION"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "mdef-snr-db",
      metric: "snr_db",
      canonicalUnit: "dB",
      minPlausible: 0.0,
      maxPlausible: 40.0,
      warningThresholdLow: 8.0,
      criticalThresholdLow: 4.0,
      expectedSamplingIntervalSeconds: 5,
      aggregationStrategy: "AVG",
      allowedAssetTypes: ["COMMUNICATION"],
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
  ],

  // ─── 3. Maintenance Events ──────────────────────────────────────
  maintenanceEvents: [
    {
      id: "maint-maitri-gen1-001",
      stationId: "station-maitri",
      assetId: "asset-maitri-gen-1",
      maintenanceType: "PREVENTIVE",
      scheduledAt: new Date("2026-09-15T08:00:00Z"),
      completedAt: new Date("2026-09-15T12:30:00Z"),
      notes: "250-hour routine oil change, fuel pre-filter replacement, injector nozzle inspection.",
      partsUsed: ["Aviation-grade Arctic synthetic oil 15W-40 (45L)", "Donaldson fuel separator element (2x)"],
      result: "SUCCESS",
      createdAt: new Date("2026-09-15T08:00:00Z"),
    },
    {
      id: "maint-maitri-wtr-001",
      stationId: "station-maitri",
      assetId: "asset-maitri-water-1",
      maintenanceType: "INSPECTION",
      scheduledAt: new Date("2026-09-20T10:00:00Z"),
      completedAt: new Date("2026-09-20T11:45:00Z"),
      notes: "Priyadarshini lake pump heat-tracing cable thermal resistance test. Insulation resistance measured at 120 M-ohm.",
      partsUsed: ["Thermal heat-shrink sleeve (2m)"],
      result: "SUCCESS",
      createdAt: new Date("2026-09-20T10:00:00Z"),
    },
    {
      id: "maint-bharati-chp1-001",
      stationId: "station-bharati",
      assetId: "asset-bharati-chp-1",
      maintenanceType: "CORRECTIVE",
      scheduledAt: new Date("2026-09-22T06:00:00Z"),
      completedAt: new Date("2026-09-22T09:15:00Z"),
      notes: "Exhaust gas temperature sensor thermocouple replacement due to drift on cylinder #4.",
      partsUsed: ["Type-K Arctic thermocouple probe", "High-temp gasket seal"],
      result: "SUCCESS",
      createdAt: new Date("2026-09-22T06:00:00Z"),
    },
    {
      id: "maint-bharati-ro-001",
      stationId: "station-bharati",
      assetId: "asset-bharati-ro-1",
      maintenanceType: "PREVENTIVE",
      scheduledAt: new Date("2026-09-26T14:00:00Z"),
      completedAt: new Date("2026-09-26T17:00:00Z"),
      notes: "Desalination membrane chemical wash and citric acid descaling. Feed permeate conductivity returned to 140 ppm.",
      partsUsed: ["RO membrane cleaner compound B (5 kg)", "Micron sediment pre-filter cartridge (1x)"],
      result: "SUCCESS",
      createdAt: new Date("2026-09-26T14:00:00Z"),
    },
  ],

  // ─── 4. Operators & Roles ───────────────────────────────────────
  operators: [
    {
      id: "op-admin-01",
      username: "admin",
      fullName: "Col. Rajesh Sharma (Director of Polar Ops)",
      role: "ADMIN",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-admin-legacy",
      username: "rsharma",
      fullName: "Col. Rajesh Sharma",
      role: "ADMIN",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-ops-maitri",
      username: "officer.maitri",
      fullName: "Cmdr. Vikram Negi (Maitri Station Leader)",
      role: "OPERATOR",
      stationId: "station-maitri",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-ops-bharati",
      username: "officer.bharati",
      fullName: "Lt. Cmdr. Ananya Roy (Bharati Station Leader)",
      role: "OPERATOR",
      stationId: "station-bharati",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-eng-01",
      username: "engineer.patel",
      fullName: "Dr. Pranav Deshmukh (Chief Station Engineer)",
      role: "ENGINEER",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-eng-maitri",
      username: "pdeshmukh",
      fullName: "Dr. Pranav Deshmukh",
      role: "ENGINEER",
      stationId: "station-maitri",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-log-01",
      username: "logistics.sharma",
      fullName: "Kavita Raman (Antarctic Resupply Officer)",
      role: "LOGISTICS",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-log-maitri",
      username: "kraman",
      fullName: "Kavita Raman",
      role: "LOGISTICS",
      stationId: "station-maitri",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-eng-bharati",
      username: "sbanerjee",
      fullName: "Sourav Banerjee",
      role: "ENGINEER",
      stationId: "station-bharati",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-viewer-01",
      username: "viewer",
      fullName: "Antarctic Operations Center Duty Desk",
      role: "VIEWER",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
    {
      id: "op-viewer-ops",
      username: "opsviewer",
      fullName: "Antarctic Operations Center Duty Desk",
      role: "VIEWER",
      createdAt: new Date("2026-09-01T00:00:00Z"),
    },
  ],

  // ─── 5. Audit Events ────────────────────────────────────────────
  auditEvents: [
    {
      id: "audit-001",
      operatorId: "op-admin-01",
      action: "STATION_SYNC_POLICY_UPDATE",
      targetType: "STATION",
      targetId: "station-maitri",
      previousState: { dataMode: "EXTERNAL", syncIntervalSeconds: 60 },
      newState: { dataMode: "SIMULATED", syncIntervalSeconds: 3 },
      result: "SUCCESS",
      correlationId: "corr-sync-setup-01",
      createdAt: new Date("2026-09-28T09:00:00Z"),
    },
    {
      id: "audit-002",
      operatorId: "op-eng-maitri",
      action: "ACKNOWLEDGE_ALERT",
      targetType: "ALERT",
      targetId: "alert-maitri-gen-001",
      previousState: { status: "OPEN" },
      newState: { status: "ACKNOWLEDGED", comment: "Inspected fuel filter pressure differential" },
      result: "SUCCESS",
      correlationId: "corr-alert-ack-99",
      createdAt: new Date("2026-09-28T16:20:00Z"),
    },
    {
      id: "audit-003",
      operatorId: "op-eng-bharati",
      action: "SIMULATED_TEST_RUN",
      targetType: "ASSET",
      targetId: "asset-bharati-chp-2",
      previousState: { status: "MAINTENANCE" },
      newState: { status: "OPERATIONAL" },
      result: "SUCCESS",
      correlationId: "corr-chp2-test-01",
      createdAt: new Date("2026-09-29T02:15:00Z"),
    },
  ],

  // ─── 6. Cargo Missions ──────────────────────────────────────────
  cargoMissions: [
    {
      id: "mission-44-isea-01",
      code: "ISEA-44-SOUTH-RUN",
      name: "44th Indian Antarctic Expedition Resupply Voyage (MV Vasiliy Golovnin)",
      origin: "Cape Town Port Berth 5",
      destinationStationId: "station-maitri",
      vesselOrAircraft: "MV Vasiliy Golovnin (Ice-Class Cargo/Tanker)",
      status: "IN_TRANSIT" as const,
      departureDate: new Date("2026-09-18T10:00:00Z"),
      eta: new Date(Date.now() + 18 * 24 * 3600 * 1000), // In 18 days
      etaConfidencePct: 91.5,
      maxPayloadKg: 450000,
      currentPayloadKg: 382000,
      weatherRisk: "MODERATE" as const,
      deliveryBufferDays: 14,
      createdAt: new Date("2026-09-10T00:00:00Z"),
    },
    {
      id: "mission-air-il76-02",
      code: "DROMLAN-IL76-SORTIE-3",
      name: "DROMLAN Airlink Heavy Airlift (Cape Town to ALCI Blue Ice Runway)",
      origin: "Cape Town International",
      destinationStationId: "station-maitri",
      vesselOrAircraft: "Ilyushin Il-76TD-90VD",
      status: "PLANNED" as const,
      departureDate: new Date(Date.now() + 5 * 24 * 3600 * 1000),
      eta: new Date(Date.now() + 6 * 24 * 3600 * 1000),
      etaConfidencePct: 84.0,
      maxPayloadKg: 28000,
      currentPayloadKg: 24500,
      weatherRisk: "LOW" as const,
      deliveryBufferDays: 7,
      createdAt: new Date("2026-09-25T00:00:00Z"),
    },
    {
      id: "mission-bharati-sea-03",
      code: "BHARATI-EXPED-SUPPLY-4",
      name: "Larsemann Hills Annual Coastal Resupply Voyage",
      origin: "Goa Mormugao Port",
      destinationStationId: "station-bharati",
      vesselOrAircraft: "Icebreaker SA Agulhas II",
      status: "PROCESSING" as const,
      departureDate: new Date(Date.now() + 12 * 24 * 3600 * 1000),
      eta: new Date(Date.now() + 35 * 24 * 3600 * 1000),
      etaConfidencePct: 94.0,
      maxPayloadKg: 620000,
      currentPayloadKg: 510000,
      weatherRisk: "LOW" as const,
      deliveryBufferDays: 21,
      createdAt: new Date("2026-09-15T00:00:00Z"),
    },
  ],

  // ─── 7. Cargo Requisitions ──────────────────────────────────────
  cargoRequisitions: [
    {
      id: "req-maitri-diesel-01",
      stationId: "station-maitri",
      itemId: "inv-maitri-fuel-1",
      itemName: "Arctic Winter Diesel Grade A1 (-50°C pour point)",
      category: "FUEL",
      requestedQuantity: 85000,
      unit: "Liters",
      priority: "CRITICAL" as const,
      status: "IN_TRANSIT" as const,
      reason: "Pre-winter seasonal tank replenishment to maintain 180-day survival reserve buffer",
      requestedBy: "officer.maitri",
      approvedBy: "admin",
      missionId: "mission-44-isea-01",
      createdAt: new Date("2026-09-12T00:00:00Z"),
      updatedAt: new Date("2026-09-15T00:00:00Z"),
    },
    {
      id: "req-maitri-spares-02",
      stationId: "station-maitri",
      itemId: "inv-maitri-spares-1",
      itemName: "Cummins KTA-19 Alternator Maintenance Kit & Injectors",
      category: "SPARES",
      requestedQuantity: 6,
      unit: "Sets",
      priority: "HIGH" as const,
      status: "AUTHORITY_APPROVED" as const,
      reason: "500-hour planned major overhaul spares for Primary Generator GEN-01",
      requestedBy: "engineer.patel",
      approvedBy: "admin",
      missionId: "mission-air-il76-02",
      createdAt: new Date("2026-09-22T00:00:00Z"),
      updatedAt: new Date("2026-09-24T00:00:00Z"),
    },
    {
      id: "req-maitri-med-03",
      stationId: "station-maitri",
      itemId: "inv-maitri-med-1",
      itemName: "Medical Oxygen Cylinders 50L (200 bar)",
      category: "MEDICAL",
      requestedQuantity: 12,
      unit: "Cylinders",
      priority: "HIGH" as const,
      status: "REQUESTED" as const,
      reason: "Hospital emergency bay stock replenishment",
      requestedBy: "officer.maitri",
      createdAt: new Date("2026-09-28T00:00:00Z"),
      updatedAt: new Date("2026-09-28T00:00:00Z"),
    },
    {
      id: "req-bharati-ro-01",
      stationId: "station-bharati",
      itemId: "inv-bharati-spares-1",
      itemName: "Dow Filmtec Sea-Water Desalination Membranes SW30HR",
      category: "SPARES",
      requestedQuantity: 8,
      unit: "Modules",
      priority: "HIGH" as const,
      status: "PROCESSING" as const,
      reason: "Reverse Osmosis life-support plant seasonal membrane rotation",
      requestedBy: "officer.bharati",
      approvedBy: "admin",
      missionId: "mission-bharati-sea-03",
      createdAt: new Date("2026-09-20T00:00:00Z"),
      updatedAt: new Date("2026-09-22T00:00:00Z"),
    },
  ],

  // ─── 8. Station Thresholds ──────────────────────────────────────
  stationThresholds: [
    {
      id: "thresh-maitri-gen-temp",
      stationId: "station-maitri",
      metric: "engine_temp_c",
      warningThresholdLow: 60.0,
      warningThresholdHigh: 82.0,
      criticalThresholdLow: 50.0,
      criticalThresholdHigh: 90.0,
      updatedBy: "admin",
      updatedAt: new Date("2026-09-01T00:00:00Z"),
      comment: "Manufacturer technical manual maximum continuous operating temperature",
    },
    {
      id: "thresh-maitri-bat-soc",
      stationId: "station-maitri",
      metric: "battery_soc_pct",
      warningThresholdLow: 40.0,
      warningThresholdHigh: 98.0,
      criticalThresholdLow: 25.0,
      criticalThresholdHigh: 100.0,
      updatedBy: "admin",
      updatedAt: new Date("2026-09-01T00:00:00Z"),
      comment: "Sub-zero buffer limit preventing irreversible lithium cell degradation",
    },
    {
      id: "thresh-maitri-fuel-level",
      stationId: "station-maitri",
      metric: "fuel_level_liters",
      warningThresholdLow: 25000.0,
      criticalThresholdLow: 15000.0,
      updatedBy: "admin",
      updatedAt: new Date("2026-09-01T00:00:00Z"),
      comment: "30-day minimum survival reserve floor for Maitri winter station",
    },
    {
      id: "thresh-bharati-chp-vib",
      stationId: "station-bharati",
      metric: "vibration_mms",
      warningThresholdHigh: 4.5,
      criticalThresholdHigh: 7.0,
      updatedBy: "admin",
      updatedAt: new Date("2026-09-01T00:00:00Z"),
      comment: "ISO 10816-3 mechanical vibration limit for rotating tri-gen machinery",
    },
  ],

  // ─── 9. Operational Mission Events ──────────────────────────────
  missionEvents: [
    {
      id: "event-m-01",
      stationId: "station-maitri",
      category: "SYSTEM" as const,
      severity: "INFO" as const,
      title: "Station Digital Twin Initialized",
      description: "State registry synchronized with physical telemetry edge buffer",
      source: "SIMULATOR",
      provenanceType: "MEASURED",
      zone: "Central Operations",
      metadata: { initialAssetsCount: 6, mode: "NORMAL" },
      createdAt: new Date("2026-09-28T00:00:00Z"),
    },
    {
      id: "event-m-02",
      stationId: "station-maitri",
      category: "ENERGY" as const,
      severity: "INFO" as const,
      title: "Solar Inverter Synchronization",
      description: "Roof PV array energized at 14.2 kW during clear antarctic spring insolation",
      source: "MEASURED",
      provenanceType: "MEASURED",
      zone: "Energy Substation",
      metadata: { irradianceWm2: 520, inverterKw: 14.2 },
      createdAt: new Date("2026-09-29T11:00:00Z"),
    },
    {
      id: "event-m-03",
      stationId: "station-maitri",
      category: "LOGISTICS" as const,
      severity: "INFO" as const,
      title: "Annual Fuel Requisition Authorized",
      description: "85,000L Arctic A1 diesel cargo allocated to MV Vasiliy Golovnin sortie",
      source: "OPERATOR",
      provenanceType: "OPERATOR",
      zone: "Main Tank Farm",
      metadata: { missionCode: "ISEA-44-SOUTH-RUN", volumeLiters: 85000 },
      createdAt: new Date("2026-09-29T14:30:00Z"),
    },
    {
      id: "event-m-04",
      stationId: "station-maitri",
      category: "COMMUNICATION" as const,
      severity: "WARNING" as const,
      title: "Geomagnetic Solar Flux Warning",
      description: "NOAA Space Weather alert Kp=6.5; Ku-band link derated to 64 kbps Fast-Lane mode",
      source: "EXTERNAL",
      provenanceType: "EXTERNAL",
      zone: "Comms Radome",
      metadata: { kpIndex: 6.5, linkLatencyMs: 780 },
      createdAt: new Date("2026-09-30T04:15:00Z"),
    },
  ],
};
